import {sql} from "@vercel/postgres";
import {cookies} from "next/headers";
import {NextResponse} from "next/server";
export const dynamic="force-dynamic";
async function init(){await sql`CREATE TABLE IF NOT EXISTS links(id SERIAL PRIMARY KEY,slug TEXT UNIQUE NOT NULL,title TEXT NOT NULL,image TEXT NOT NULL,destination TEXT NOT NULL,owner_id TEXT NOT NULL,created_at TIMESTAMPTZ DEFAULT NOW())`}
function owner(){const c=cookies();let id=c.get("ln_browser_id")?.value,newOne=false;if(!id){id=crypto.randomUUID();newOne=true}return{id,newOne}}
function out(data,status,o){const r=NextResponse.json(data,{status});if(o?.newOne)r.cookies.set("ln_browser_id",o.id,{httpOnly:true,sameSite:"lax",secure:true,maxAge:157680000,path:"/"});return r}
export async function GET(){try{const o=owner();await init();const {rows}=await sql`SELECT id,slug,title,image,destination,created_at FROM links WHERE owner_id=${o.id} ORDER BY id DESC`;return out({links:rows},200,o)}catch(e){console.error(e);return NextResponse.json({error:"Database not connected. Connect Vercel Postgres and redeploy."},{status:500})}}
export async function POST(req){try{const o=owner(),b=await req.json();const slug=String(b.slug||"").trim().toLowerCase().replace(/[^a-z0-9_-]+/g,"-"),title=String(b.title||"").trim(),image=String(b.image||"").trim(),destination=String(b.destination||"").trim();if(!slug||!title||!image||!destination)return out({error:"URL slug, title, photo URL and destination URL are required."},400,o);if(!/^https?:\/\//i.test(image)||!/^https?:\/\//i.test(destination))return out({error:"Photo and destination must start with http:// or https://."},400,o);await init();try{const {rows}=await sql`INSERT INTO links(slug,title,image,destination,owner_id) VALUES(${slug},${title},${image},${destination},${o.id}) RETURNING id,slug,title,image,destination,created_at`;return out({link:rows[0]},201,o)}catch(e){if(String(e.message||"").toLowerCase().includes("unique"))return out({error:"That URL slug already exists."},409,o);throw e}}catch(e){console.error(e);return NextResponse.json({error:"Could not create link. Check the Vercel database connection."},{status:500})}}
export async function DELETE(req){try{const o=owner(),{slug}=await req.json();await init();await sql`DELETE FROM links WHERE slug=${slug} AND owner_id=${o.id}`;return out({ok:true},200,o)}catch(e){return NextResponse.json({error:"Could not delete link."},{status:500})}}