"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
export default function Dashboard(){const[links,setLinks]=useState([]),[form,setForm]=useState({slug:"",title:"",image:"",destination:""}),[copied,setCopied]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");
async function load(){setLoading(true);try{const r=await fetch("/api/links",{cache:"no-store"}),d=await r.json();if(!r.ok){setError(d.error||"Database error");return}setError("");setLinks(d.links||[])}catch{setError("Cannot connect to server.")}finally{setLoading(false)}}
useEffect(()=>{load()},[]);
async function create(e){e.preventDefault();const r=await fetch("/api/links",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}),d=await r.json();if(!r.ok)return setError(d.error||"Create failed");setLinks([d.link,...links]);setForm({slug:"",title:"",image:"",destination:""});setError("")}
async function copy(slug){await navigator.clipboard.writeText(location.origin+"/go/"+slug);setCopied(slug);setTimeout(()=>setCopied(""),1300)}
async function del(slug){if(!confirm("Delete this link?"))return;const r=await fetch("/api/links",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({slug})});if(!r.ok)return setError("Delete failed");setLinks(links.filter(x=>x.slug!==slug))}
return <main className="dashboard"><aside><div className="brand"><span className="logo">↗</span><div><b>LinkNest</b><small>CONTROL CENTER</small></div></div><div className="label">WORKSPACE</div><a className="active">Overview</a><a href="#create">Create Link</a><a href="#links">My Links</a><div className="online">● Browser Workspace</div></aside><section className="main"><div className="head"><div><span className="tag">MY WORKSPACE</span><h1>Link Dashboard</h1><p>Create, copy and delete your links.</p></div><Link href="/" className="ghost">Home ↗</Link></div>{error&&<div className="error">{error}</div>}<div className="grid"><form id="create" className="card" onSubmit={create}><h2>Create New Link</h2><label>URL SLUG<input required pattern="[A-Za-z0-9_-]+" value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})} placeholder="example-link"/></label><label>TITLE<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="My photo"/></label><label>PHOTO URL<input required type="url" value={form.image} onChange={e=>setForm({...form,image:e.target.value})} placeholder="https://example.com/photo.jpg"/></label>{form.image&&<div className="preview"><img src={form.image} alt="Preview"/></div>}<label>DESTINATION URL<input required type="url" value={form.destination} onChange={e=>setForm({...form,destination:e.target.value})} placeholder="https://example.com"/></label><button className="primary wide">Create Link →</button></form><section id="links" className="card"><div className="listHead"><h2>My Links</h2><strong>{links.length}</strong></div>{loading?<div className="empty">Loading...</div>:!links.length?<div className="empty">No links created in this browser.</div>:links.map(x=><div className="item" key={x.slug}><img src={x.image} alt=""/><div className="info"><b>{x.title}</b><small>{location.origin}/go/{x.slug}</small></div><button onClick={()=>copy(x.slug)}>{copied===x.slug?"Copied":"Copy"}</button><a href={"/go/"+x.slug} target="_blank">Open</a><button className="delete" onClick={()=>del(x.slug)}>×</button></div>)}</section></div></section></main>}